### ISSUE TITLE
Możliwe dodanie 2x tej samej książki.

### ISSUE THREAD

**Issue by lechu7** [danieln96/BookWeb_SIAG#14]

**Comment by danieln96** [comment]
Poprawione do sprawdzenia

**Comment by lechu7** [comment]
Tylko może być przypadek że jest ten sam tytuł a inny autor. Daj warunek że tytuł i autor tacy sami.

**Comment by danieln96** [comment]
Do sprawdzenia i zamknięcia

**Comment by lechu7** [comment]
Działa :)
