### ISSUE TITLE
BUG. Hasło w Rejestracja.

### ISSUE THREAD

**Issue by lechu7** [danieln96/BookWeb_SIAG#16]
Po podaniu prawidłowego hasła zawsze wyświetla sie "Hasło musi mieć minimum 8 znaków, jedną dużą literę i jedną cyfrę"

**Comment by danieln96** [comment]
Poprawione do sprawdzenia

**Comment by lechu7** [comment]
Dodałbym funkcję TRIM do maila ponieważ w mailu nie mogą być spacje.
Gdy dam spację przed mailem to po kliknięciu nic się nie dzieje.

**Comment by danieln96** [comment]
U mnie działa. Zamykam
