### ISSUE TITLE
FEATURE. Button powrót w Lista Książek

### ISSUE THREAD

**Issue by lechu7** [danieln96/BookWeb_SIAG#17]
Brak przycisku powróć po wejściu na liście książek w jakąś książkę. 
Po wejściu w książkę na ostatniej stronie musimy wybrać przycisk "lista książek" który znów przeniesie nas na 1 stronę.

**Comment by danieln96** [comment]
Dodane do sprawdzenia

**Comment by lechu7** [comment]
Wydaje mi się że bardziej intuicyjne będzie gdy będzie ten button na górze.
Mógłbyś to zmienić??

**Comment by danieln96** [comment]
Będzie zmienione
