### ISSUE TITLE
Wyszukiwarka książek

### ISSUE THREAD

**Issue by danieln96** [danieln96/BookWeb_SIAG#2]

**Comment by lechu7** [comment]
Wyszukiwarka i sortowanie powinno być.
Dobrze jakby była również filtracja.

**Comment by danieln96** [comment]
Do sprawdzenia

**Comment by lechu7** [comment]
Usuń spację na początku i na końcu wpisywanego tekstu. Jak dam spację a potem tytuł to nie znajdzie.

**Comment by lechu7** [comment]
To już chyba działa, co nie??

**Comment by danieln96** [comment]
Działa. Zamknij jak wszystko ok

**Comment by lechu7** [comment]
Działa :)
