### ISSUE TITLE
BUG. Klawisz Powrót Po kliknięciu w książkę.

### ISSUE THREAD

**Issue by lechu7** [danieln96/BookWeb_SIAG#22]

**Comment by lechu7** [comment]
Jak kliknę w książkę (https://siag-bookweb.herokuapp.com/books/1) i usunę jako admin opinię to nie działa klawisz powrót :-1:

**Comment by danieln96** [comment]
Po prostu pobiera ostatni adres
Jakbys wszedl z innej strony pod ten adres to by tam powrocilo
Zmienie to

**Comment by danieln96** [comment]
Poprawione do sprawdzenia i zakmniecia

**Comment by lechu7** [comment]
W ogóle nie działa klawisz powrót :-1:

**Comment by danieln96** [comment]
Poprawione. Teraz będzie śmigać jak ta lala. Do sprawdzenia

**Comment by lechu7** [comment]
Działa :)
