### ISSUE TITLE
FEATURE. Jeden użytkownik->jedna ocena/opinia w jednej książce

### ISSUE THREAD

**Issue by lechu7** [danieln96/BookWeb_SIAG#24]
Jeden użytkownik może dodać do jednej książki jedną opinie i jedną ocenę. 
Powinna być opcja edycji dotychczasowej oceny.

**Comment by danieln96** [comment]
Do sprawdzenia i zakmniecia

**Comment by lechu7** [comment]
Dodaj tylko tło do komunikatu bo tekst "Dodałeś już opinię do tej książki" jest nieczytelny bez jakiegokolwiek tła.

**Comment by danieln96** [comment]
Dodane. Do sprawdzenia

**Comment by lechu7** [comment]
Działa :)
