### ISSUE TITLE
Alert przy wyszukiwaniu książęk

### ISSUE THREAD

**Issue by yankes2014** [danieln96/BookWeb_SIAG#25]
Po kliknięciu wyszukaj książke, taką której nie ma w bazie powinien pokazywać się alert "Nie znaleziono książki o podanej frazie". Na chwilę obecną nie jest wyświetlane nic, obstawiam że jest po prostu wyświetlana pusta lista książek. Potrzebne mi to do testowania.

**Comment by danieln96** [comment]
Zrobione do sprawdzenia

**Comment by yankes2014** [comment]
Działa jak natura chciała
