### ISSUE TITLE
API users+opinion

### ISSUE THREAD

**Issue by lechu7** [danieln96/BookWeb_SIAG#30]
JSON z kolumnami:  **login;tytuł książki; autor; opinia; ocena**

Tylko nie wiem czy ocena to ocena czy Rate 1-10 bo takie masz kolumny w DB.

**Comment by danieln96** [comment]
http://siag-bookweb.herokuapp.com/api/users/json?opinions=true
Do zamkniecia

**Comment by lechu7** [comment]
A nie dałoby się skleić tego JSON tak jak napisałem?? Lepiej po stronie DB niż u mnie

**Comment by lechu7** [comment]
INNER JOIN i jazda ⚾️

**Comment by lechu7** [comment]
Sam se zrobiłem 👎
