### ISSUE TITLE
Brak możliwości wejścia w panel "Użytkownicy" zalogowany jako User.

### ISSUE THREAD

**Issue by lechu7** [danieln96/BookWeb_SIAG#32]

**Comment by lechu7** [comment]
Od komentować w testach dodawanie listy u siebie jak Daniel poprawi BUG.

**Comment by danieln96** [comment]
Poprawione

**Comment by lechu7** [comment]
![screenshot 2018-05-22 18-18-38](https://user-images.githubusercontent.com/24591899/40375717-ad50fabe-5dec-11e8-9eb9-5831b42e067c.jpg)

**Comment by lechu7** [comment]
Działa :)
