### ISSUE TITLE
walidacja książek

### ISSUE THREAD

**Issue by malinator10000** [danieln96/BookWeb_SIAG#37]
można się zastanowić nad walidacją dodawanych książek, chociaż jeżeli tylko administrator może je dodawać, to nie wiem, czy to konieczne. Daj znać, czy będziesz cos zmieniał pod tym względem

**Comment by malinator10000** [comment]
mam na myśli ograniczenia w długości tytułów i takie tam

**Comment by danieln96** [comment]
Nie zmieniam na razie
